---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: desec-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCtVp3QfysYBqJawErSb4K5XyvJWOBC/z/6soS/OHa5H8vtkMkZ2tO7pb8jxhxV7hjIhe60Th0fEFoDtEA+/vx6S7rC4SMzDSp2urSaqFBGaPyIroFlCsP05uh5KcgcsXyVGrzPRKivASROv1htzzv8IFKGQRg+/lSGRn7O9A76u18/f+wNgH0B+aBv1KTSF4MqMqlkl3CkJbm18bZYwxnUnnaopEFDn3imT2KbgpHWK/ydqz3tG1y1KuvxORknBO4fogB9Z2iX4oehz6V3rv/bhBjA6TPd72MvDOowgCTX0sdi+x/xmFyd53CEBBaqQH2bnA3U5ENV6kF9DZDRnzIAFiXXHh/PIzLVgjOfrHeICMbZbRHMJLfILtQ3Qe1xR5r4q7YG0u+GkKAoSMVHvNHz/dgTJ4HwVuvHU7set4q5JCBYhD8VxQvZq81d1svHJmzAPZa7tcHUzwgQizWdMoVVXMGk8xw7EJMKv1+Urfo8FS4Fr8IkyCzjHR5gfZhGTO/SUayEqudrNUTRjSaK71XlaJRyUVb5rMVQYI8GVb1c0Zh659VXLNtP/5k5Qflm2c5a4BYbilyiV8b5Vnz4JaALWxXeQVrcJCrC2zcStHJztrLfnp4+/MMM0v/HRYLKmLxDOWr4mXYw3XL8dwb8ITdeSyZVAVAIftyAcTTIUahi5cqi9oulDg9uvX1N7l3xxXwp9A5M
  template:
    metadata:
      name: desec-token
      namespace: cert-manager
