---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: desec-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCfaUrRr9b1yyjkU5n+Mjy0irE3hMkK1dJYtApP2krgtlg3kG4y0uya3PeAfM3TqNZIFJKZMJWlQf7Nf5al6g5Fvop6rOBXgFZ5enhNgEHeLFAa6gbDz0q6joXimFU4HVoxbVF5jPiC3wX9AS+E6t5ZTXei8ss4iPqH2lP5Jviq9+/qf2xaVcdcXzsDpCXHRQVBVl1v4qglknfG1y92hjXlr2BL/fhBQL7nvP52nP9KcZAIlvWswc3LgjetNI0Kdvw+Fn0IePZQaPxBSqyzhCiq6Fsq1so2aIe88HXIeJ/4jRRPu3zepLEVrf+ErA8Scgl5H7hm+W8YGujHxwjhMbo9n4t048+k7P9rF8lt4+CbFtkHTRPWhA+dU+asq8iW++w/R4gbFJF2rg66BCzm8EOt/jRfwi8D3uvLQW8Jedd4FILVkkJSBou86TrRoLkXE3T3+8I+HjD6h5KmO54RV0rGA7n+Sc8VvzIQ2ykud94rBHrbmfcHfd5ku1IKhE7Vspk4jpxbKFdL3TV+q9deGzV0gdZtziUNOjrP26f8UBSGJ3r4d4B5tJfTR1iEdKCAgrCT+NBkIBkd3hHV9tvA4u8p6e/OcEP4Zc32yfQStk9/0RvyMTg5P++AjInUpXtAZL6jMB6DzER0gJaIasDghOmHM3ctV52K1/JhQX0fTXjcW1MyiQptHau8YWHnyXGFFIuSGBkA
  template:
    metadata:
      name: desec-token
      namespace: cert-manager
