---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: onlyoffice-secrets
  namespace: onlyoffice
spec:
  encryptedData:
    jwt-secret: AgChCGUW8E+MnxtvZqiFGPpXspjc1/qxgOX+maRjOdZvOBhM1wAKVgkwFzGH7AptMpadQsOzYVCtG8iWaR5MI46c5JsnEz6TnmrI3DT0afXH4C0f/0daggFSOpPyi150bogdjoH+zPddnrG3JZZvpZaoq+nZXG08CaceAVqa/59pslad9tsx1WDJFwGCxMdUf6DtNJJZqrtELCHBRfX9pD+JsH7rLaAM38P49JU6D/TkAFOxgdWtZe4qDvFzliz145axsWKhOoFkYyFllidExkkay811dihMYhBzWQEoOp1JTFGVu5fCbi9NTs0FRZZJdUGqnEo7Jy6QxBu3FaBdz23ya2l5TJSiYBy7NLgfxCoeosiiF9YZXGrhCibQhuMDgMppWano2QJB7BPdGm8EYAUPWCQIUBU1HukH6XEk9V8dWcuOT4n8EY1DFMzIMD1Di4dGtApajJklVWD+AA874e6Ka0lJDC5J4gqNfrec2oIwXsg5vILauLPkqvyh8lOJPANxcUTpR8/7rxfYkCin5+3jISc0+UkAhHQbvYwtmo6hBHqeFh7g+/y8l4iImN96ztx6FuPcEqBTXnp38/A5eAyIA93p3tCUrcdewN7Smd/uYIKyi1wpV6HfsVfMnT9yj+l+UV27oVPQ8q1SM20dbakK14Dl809WVNSnuy1yn8vxtHjIJGOBnxGIPB5aOFI1epmGNk7GsIkdfX5QRvp6pgCFhrKuSqJ/6/jZpThC8N4xZA==
  template:
    metadata:
      name: onlyoffice-secrets
      namespace: onlyoffice
