---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: onlyoffice-secrets
  namespace: onlyoffice
spec:
  encryptedData:
    jwt-secret: AgBa/gwUk5S1IOo5xUkq7vdjlwmYkkWWRVkUUiy78TbR//wQP/ERq/caLABTnZmHx1XTjw6cJprVpt0bm0+htM2V03yfJu6hZdri5+5oH/zLxboVdN0bJbSantG0fWlJIqE7jeJo9GPe/uVNaJiZKLezRCuqUjI7F552fvG4UjgWrSNoFs1e+InddaddsHpP/EViM9rWpucKgNfm/ODSIEoQqQ2kqmJY42E7I5yXoAJ5K/wFZ+bv8YDg3em8KxFRWc8y99jn2QNHoiIjLAHwopBP4/xg2lK0LilNoBiFK2c5BS5DH8fwM9TT5EoVuUObFwtLbHAjiugRtlndwtQCnV7H1xM5YvrgcdWHOZcFxiIJXQzwP80BvOUk6hGc/Ab2IhVvlfXuq1QnO+ZD9Hcbrs2vc5G8yvq4+DFS6CUYJ8jxBJYQcVBNUs18ZzJLnw3WsnREuehk6+3Yr9yQ7ow36Z+Z/GbGNRHMd+IxzCFTtYEho5UXiDgCcwo7puy0lhe/V81FxgZcpsr9ps1dwUqMNWZEkYvttpKta064CWTH52y0wb8UCXXws699nG/ENOfJpFIcfDiKQ3e7pDA6iNe7obhFCM2E/k0uVYOnUGSq8k2ZyGC5GD7RbTpuT3x3BPS88Wtkrr3kpiyml/cJ0Ueljb0XWjZ0kG7E5WfGt9UlZ94mf/Vmo1ZOXBZ3kv1oyX21xQNCeO053JP+B181Hi6wzoUrrqI6FJ301yOW7jyVh8qCyQ==
  template:
    metadata:
      name: onlyoffice-secrets
      namespace: onlyoffice
