---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: desec-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAwsXNP2aySnTo6B0Xg9IWyF2odRdrg5sNy/IwR8BlurNh9UMBy7jVH5tghYKwkXue8Fu7jk9dlt2hAkyy6DYpOnDypNzdCEGsxj3XwXBKpwGjBLw9ISFWIxwXKcS+8y4rhBoSuz/JuemyUO/iXxOPyCz6Pp1OyagQ1tjOQfH7g3aUqdw+9s5qIKFcHzT4H64XNIGUFvgzGt90GZWu2hNpYNSyMCuQcJ3yp59crUlgK6yHrKvYEZr5ul70JNxdCY06ickeLmnQRZ1Jtpp1A05z/A5U5/NjLQjABq1g1TKMesg8NTnW3cQNBeoJ6l+Yb70x7kfVvNUKcMwm93MTNip/UuzXT18nBy/scNOtBk3cvHit2CdGmQyuM3rGgKyag83vVzgJWH7eNZoG6wJp4gN4hRStqaTlk8BNJ681KeIz/4bDnIjV8uzwRgCrt+RZVHiorotrknyrPEe+d3FW6zNbnRuBrwi1GoOLsMa6YVOFwc9AXmGVciFc5BtaVdjL4ziLESyYNd7fxiihAGNkk5bM3grFOZxccB8xxJ+1W47ab0broCENN2xo2AexrZoOLmeLRrfgAEDLuTriuJJbyiLr6LtPsfs4D1pXLg7vh9ICQAayK4PdxFAKgZPWpRthvDr+LAzey3lIPC/vkdvkX4aWNMsyPVVFgyazBHcBnwhmabbxp5Y+Iw1pbZlFFMVLOE+uz8G7+G5zFveEpDQ==
  template:
    metadata:
      name: desec-token
      namespace: cert-manager
