---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dyndns-strato-credentials
  namespace: dyndns-updater
spec:
  encryptedData:
    password: AgApELtBmWTskqx+qEehqGECjMgURmRZLxguz7FQbIGiXwVMLwBLSAGk9LXjek0Ef6xFVgCnUO7JFC5ycXbFnJk0wKrJmVA2zVb8/AiyUBUtHRubWIGi+0685g3vRFVeFl+PSCRe5c1jsW/4xyNgzgCj7Csfa16/mgGDSFhjdpkF6NgibpQWS077od4oj8uSfg1Cx2Ag5v7wYvzgK9petX/W0zqAXjE9Rjf0BIPSesdfmapDy6Mdlxpsubn53593Aev5WpeWyVqIWb1G7Tzzjrkk05Pj7fxUs90Q2OBhzi0gNU8GsUFP4nRv7x6t1pyEgmklBwkHGnZPMRb+l9xdUvbrlEd3wX128N0o+IrJcEvZvwJ3kmBANxliSCZwuZq+xeDsCH2SnfAlB1hhRq8Yi9TRsxq/xUTn8UUobpFOSUz3Kw4ftJbXiv3fY61inLhPbbq0qmPV5GzFLyHm9qHaYfk46jxmAnbrPaF0Py7Zugh9Qcv41uva6ZPKy+S0KcCRow9m6cZ29+KIBRkXojSlCami2S1Q7pD/5i65wqCofiir1tGsXtWNmmIgGJNTrJGMZfcpwuBGWyONawtdrYchPCZsx0zjBqWyd7DqPoVlcmGi8pxzhtn413JaHU88dvzbCsAgyrGNMuWqT/fd+dzEIl3hDSfOnGXXEwe1vVYyiLj0XL3RbKF/UF6wI9fOiWYRk87Q1Dis
    username: AgC+I9DUl4Vx6gZ2XtnmpmwZin1HksDCyONsCHjwDKdPSDaJx5rqpYO2jfBbG1aQfMdyuOWFUeX1+Llx9/p55LEVsd+Yoerd49c5MAfohXLINrqWLvs3SjcsLHYZWWtkJet6t0ru/q6t3sXYu2W2vS5zdJsn4BxC2C26ENVuPa3hnxtHz8HOEe5Egq75eU+JMjZTG7jKI8Ye/W555QCstxGqEJCuUhkhSKfjMV3SkTsI+xEdUsBFStqVoHm4ZMpFn8ScRZ9aRhdi8j4MD0luoLhnN5PdNHEt9mdXdOBXei3DrodwKN4izqb9w7Cmrzv9TLijlb/Wi9eGs9joItwAQikGkwOblgYmtdiUf1byBLH6wbiA2V3CX27JJQpb+FqkNJkPHie/Mv+2+QjEfgf1dxHXarWFOWTIOJT6UxmLh3uPWDkGKDxMTh3sunpkr9NvmqwaMz9GeMzRLekTEZqj8N16Kf/w37Dj2LROELHvXAcGXSF6XQybsKjriO8RTJ25mONHWXRQEmbuPblcBCCcQ37YyMqXYG5u9+tyqScqTY+FXpd2jPCyg5C4xN6z3M2plLD6se46hqSHNdWNhrVJ/Kad11pmm3IHXCmg3FB1+HnP3tsAizhfNMVaiB9CMHyyClEJQyMhbqVZjZlvHOHbB8wcX7bqes16t9DGnPjY3m+b2LKPN0Sm0eMR2emX0lXxeXM80EVN
  template:
    metadata:
      name: dyndns-strato-credentials
      namespace: dyndns-updater
