---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: onlyoffice-secrets
  namespace: onlyoffice
spec:
  encryptedData:
    jwt-secret: AgAcv7M2XmbJIHOLytuk4lY7dNXeBilfizN5Z2JX7Ih84JhgSPenirmQ/rQfbVdAPTBF2YCEcp9keStSQrDzy+1k9xJj1EbqZUrpNEzfPr8dX+TIRgc0g3NkF63jjY73exQHHZNCsWIiTKoUJuRESiL/jJ4/qJyqfcibQnIswFT0yjw3Tc2h2/i+26LXgQbYSim4NBdsKyaZPBAb++tg3GB1JhBfvNTr+XPo6PFI8BXyZje24gPZO318VmyNT1o4E9ll5rIepjtXolItBEXR/fpeEfhjVeMfD+Ozk5GNXXS+cD3dLRG8BC1fbFmPk054YSMtdHQwo2tVQYmuDq4l/RKGw9KJA+VdADaXUIVoQb4O/X3xloPXNh5yoFFDfG40ytRO8uy5fb6Sqh2OH9aVwQDhA1vz3wa8cA+R877QpagY2pl9S/zz/2gegcbuzHmxM5SMGSjcXrAd7eq8gqG7cp0F4SB6cICvOy2lXsMc4DPenNbN3I4DsOywlZ2OXc+6ZG+S8ycX0aSpqmxWKqdS8rRZSH+9XjXE7rDjs9I3bzk2g3FwuU+9T5sVZufT4OyvdY6JJofE0PWiUTOFncWlkpR9Fzx91TvuDHGAaAlZU0EIi4975ljClImiM95FvJB+Ft1P7FdyYN1AIHN4BWu2b/RHSRmv0W854iKKUOOHrbkg+dIpUpBzQV1rCKZUVhLVvy+cjaJVMpP1/zoaEzVuTONnp6NqOs+z91zmNtElbk7SwA==
  template:
    metadata:
      name: onlyoffice-secrets
      namespace: onlyoffice
