---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: onlyoffice-secrets
  namespace: onlyoffice
spec:
  encryptedData:
    jwt-secret: AgBB7nmmAREKr5G8GMDndY8N9rLR+ok1WLwVzsjh0Gri5fdfAnJ3CUr3R8yznk6x0iDJ+505e0h/F/2PyDSj9kZC7IE/58Z5vlDaBe8+IQb/n8bTxiyi2xSYLcRWIuWMYvLURwPkjD+cMJ+c74y43c0AS5fRq0v8RC7Rf87KBy89EQdrDgZjWCt4sSvCOhvLpNeizU128/4/ILGwm1e8ZmxsgWRYiAUY7WMnjN8wm5nudTCdvg3TOwUbJhyxeaqKsEnwIRI7eJNOGhKUVwvvi6c8KZl0p9SZJs3Lqe3KWkNAKxlvtnPbQ7JZOcIcOh0H/Py6AMYgpTF5tz0urpyMvd6AivLI8EaxCQkHutN8GPZevU3L+fJICCzc+3yAwdpCWgmmP50KuFrunIypTho6xSTwJI/iPknVcq5ijNTWsjLoKmkDrR52xHtk/klR3CiZrJvqpow9O7QhKfpWAoBz3hhGgGzbp1d1+MwRwrukIG6rK9X+UDaauPqlecpJG6ozjm+9orl8Jv1j+2j/9GxUZwvP5E2o35fH/mc1XJR2x7cMi87OuDnfAtUwIIKjior4AsoatI1RRrhPxRQMdbJl5rV58xY+U3XBf56yfAJNFhwxtBCLC7t/9Kqyb1gfbjer/Q+4EFcBNjc/bQyOFFKng/uON3O1b6vMNU85QuSD4PzFTQ9vbXApvV9A/VNO8vlvtSly73q08f9UqkvuYZ3WCsVONEJ31nFZA9ndkkyU2A9smA==
  template:
    metadata:
      name: onlyoffice-secrets
      namespace: onlyoffice
