---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: onlyoffice-secrets
  namespace: onlyoffice
spec:
  encryptedData:
    jwt-secret: AgAlwNRr0QBggVceLcNA48ZGfCtUp/qc1M8KFz7f8z3EzZ0bR0SSOZOVeOaVJO0bpo9WKr0/6MrYxlFfpiydHcnTT1RUA2qO1TtCUcoCBonwg0Toj4oxtVeZdxhbXGoCUBdeQI6zuVNm1iGTjBUgvB8c6ElAmTiOE6vjJyA5Je4wkPLhfaiGX7RagjY3IxLgnVZsGdYknMEWTqQ5JCHeaz3McSveK/qyRJ7cBY8r7HQVyXvIDcwJQY3WS+a7himdYGD3dMlZeHlvT+PigN3m2kZVUym60jAXWhxNYPAfW8FX/i0ifDp1hQ2+yjRDQv7aYTEgz5C3aZJGilN4eTXLO0RomLBJTjBjXzukkf5MpKzcZIzMiymmNeDaUfONL14xpfl7F2HXY20YD0cfQn+9DDHTeLOarRrsbK7RWvslLQs55AjXhV1m7Eb+ZvmN+1vUPZraP7xyhgka8x7uJ4PSyRW/nP5Wddvq58vB4eTVdPImck9Sh+3MgegxhPNcJSKcs5OyXXm0/PHoFYj6GNAj8dRND9ZZkoYUnGeFYf/HwZZExDzWMI30YYmbpFD7wj+d3cKWNsQ78EoHx3gAi3tANa7KNihlgjJSZdEZKLFTquSWayk8GEybIYHznrxaFPOrvJrg5aT4pdcGZWAt6s+2ZDeGGbrtUcxHbOyR7m0W+737LAaFf9o8qTA5q7zKnI+1G3l1AdEpeCAnUmslklFMGkBaL9Yz5G0n/tUI2+59Sqzq+A==
  template:
    metadata:
      name: onlyoffice-secrets
      namespace: onlyoffice
