---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dyndns-strato-credentials
  namespace: dyndns-updater
spec:
  encryptedData:
    password: AgBhFFbWr0h5Tq1gUyohViSP2HuY6xIvaXwk9CDUF4ijx+OS6t11Dpu1zv9rpiQmNpKlyMwlUneteRCHhLkcdJcBLUqIbrhB20dO+vhgxh8fKTZu0mbbE3Ryio2/zE6wVdQiMXnHaZfQgfsStDHZS9KP25FhWY0LiMaYPHQdNzf+fdQt4M47oFcvodo7bLl9FAQtNDa3OGy62Ix3AEpeB7WdpzjtH9mTXUYzgBZun36DsH9CarllAiaoNXCqNBZeVmwAhzTjr5xEaYd8/D1on477hmy3CUsdqcLvyflrjFDo2Utj2VG1S8Ghz3pQqRx1mOSkQohu016XdBk9FUA2ocAJJ/BneKYQvK5vfhBCfXiw0968N8keDNTiYPFhWZdFwmXivSFGfaDHzIJliUFh6NlOT7pHUHUbEmj5Oyj/Q85dz2iffCI9Kwn1O/oFunCOx7XbB1UBd2BP5J/jEUuHQLM8YytJhfXGRyNl9v0Ps3yjL4Cw788aOgD2mpMpSarNPpNlZHyk5kmqM3YwtU+vdVW+EpKNuNPknTOeQIJwcNXGuDnPxf5teH5FoTTfRxmsiEh6jsgx5U9CFpRNRMFy111e0aNUS+x7kC5S+7WulZ08Nr+Lc9HWQ7zIj/yMqMNvBh0iL8H/AfAIVNFatJu73N1WcQYeSDjL/5hTgDsnpBCUKF3HrwZ5tUwB2urC+97va5aDN3fr
    username: AgAkhoFrHIpOsTXFXPP0sXWhzn+CHYZ1X0jSfUsVcunz3otwSqMs/lKx79xqozpURL7Ob1Xck2GRuGw+BAwwUVugHoyH9SjS11VTzKfG6nhS+oKAERGX1RhbHr/59zmgkxzXZTtIRqxtOPfCgZ17FzG1oGsAqSdo1HygOaPjXRzEM1m6vMx9fpITMBW6jqezqhvx7NQQcMEqpuPi2Z75cF2sYz2ytiuUKWDRXpCFA/t/r2M5TXGEiA/u+M0JMU3mOfeqLuGR9Pfm7U2vjM657dY47eO/AhR07MPa+l/FaO2nuCaQQNSmU5lvNQPC/Iyyzo90nH5l8sZjqxdFshVtxR1PYlBqVOsaDmEpIZYxZDitD+5Qe0fhcBzv/BylqYasR176YHJ9tI/mlLaJPU0fR4psP7o0zNRrR/+ngaMxaTFKpHyd0h0ykdZ9RmWGxlACxHSzUq+IQ2PFhJQCYz93ozwzLiPD9Uqnve9RfE4jivp10GdTBywSQM+T2GxbjsutDDpTDPJl04jtirpW6sHzG3+xwELroxD4ZUK3O3vcYkfiA2pMRcX7biaEVIus8iyyGmJE7UHfNStK6F3bGP/vsa0lzNhyt4DWrf0OxPcBj2irUnW9SI2EHNXiBRgiZfrRc9hFdxaMSvXo7hpSeZXR1741TkEJU5X/SdrC4qT1bBLNRHpz0gUw1w/uBfQxJYZ24mY7w0J6
  template:
    metadata:
      name: dyndns-strato-credentials
      namespace: dyndns-updater
