---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dyndns-strato-credentials
  namespace: dyndns-updater
spec:
  encryptedData:
    password: AgBGUxCvtLhfPivuQ1655ao8tj3nJe9kT57bIsyD8vsMOwQaP+oLwlskKvHjdyzbhlgbCXBwF7Nj1w0jj08qXRlwYbCIdk51RMa/xSDVfP8MEIQ6mNySO6L3nJt3wRtFCuY61fvjt3Cx8FvM9hGriAjwYs06e57NxwjRuKEyM5TEBVj7okd2qTtK6HEtxHdAbYpd3w41BQWlk1E7zl+Au7HWt6VJS6Jm4ZlZweUPvRBY9DnRmfywLHColKi0js/F26rBvPL5MTHyFCXb2EFCT/6B+nflU9vVqL8DhTMjYAHJNsPkVr7PvBkkxZ22sOnJ5lZiSNuoa+rvb1ZwakRqPaC1G3sSCAUK/l5mlqG2kQ4jgFNiqriH15Tin3KTFeJzn2UhjcdoXm90+Ma03SUFyqoYNr3vAXL1B1M87UiLIfSTGNF0UUVTEblER3cJujk9qNpI9lqi32jz2VNfSBbXoAHg2BFPOjEoFFaGx8gM57iuCR62uo3SV9mYBchazTU0/uJFcLOd8HzmugIGSAPIYmVrEL0XzTquzbYxkW2ptXsNkgjd0ygW2b+AnPJyEfHeBVBHnyZHDbfE4B8GZpFkTN6wDBbcKPxbeK8qPGT1/ZJoiDi4gi1AX0VcUQpKbaSgb8lsK/c1hJf5fJ9O8Pd4ZX0A8Yasbp81ocphLTWFi+6pzb5AMhfFRh/wWzq1uqoV3z8vWkYO
    username: AgB0ofCilLKDtWsuPYqv8xA734VFzgqL13R8caSNM5F8rI5tCdEafHyZofufSZhWJIeSigiC6elIN46kxkglZxFXeF3s2xzfg+5SnKPVI23j+pgV5BCI3B980xvbCQcWN1sluuWi/XyAPIz5ka8TC6KxEDO2dG+h3VnIKzLyX6Gnyerf4ByMTOQB7ZyyErOCVkqv6KcUP/r+Ew560AelVnkdyNR6wAk4OaZaauy0jMDlL77Eebcz7czWT4iocp9LQqM2OA+Jzgp2G6Ty5Fy14/avTR26kAFz5NeiqM6WNu56JFmJw3rhvxc7lbOWSSx7/SuFxj/ykpGQKdzCyc0uKoQt9wD0kJtgbRr/47CL1Yw3x5k4zFhjq574tQVPsb9oLto5TnNqpVueIN7AZbroe95OE3iCtP5by/nvx3+aton9+ABWpd3IXrMHhaV/sqcx/QbSkO7cdhZJwYHA19Ex0IDHPZhIMCZeaA529YwnuefpgjHfc09Xzx3wqQLWsCgaOWzCzOOe3SLR+3XZrZS9RB/CNqgS1PojitRJtaPXkl9WFq/EaK936U83F/VQCrEWsQwBk6wAIMhbRcixUIpGtt3zK6KrbiTE4ccfsFlo4qphgLNOovYHo5kL7zHTDhyk0EC8nmjrzS6pGNztoy8RGnDcSOxarqn3NUW+xjw1kKPZGOraFmjmgCiI0P21FawACRkiIFfA
  template:
    metadata:
      name: dyndns-strato-credentials
      namespace: dyndns-updater
